### PR TITLE
Renamed Queued and Dequeued.

### PR DESCRIPTION
**Pull request by d-stahl-ericsson**
EiffelActivityQueuedEvent and EiffelActivityDequeuedEvent renamed to
EiffelActivityTriggeredEvent and EiffelActivityCanceledEvent, respectively.

### CODE REVIEW

**Comment by p-backman-ericsson** [comment]
:+1:

**Comment by rogpers-ericsson** [comment]
Will people think that you that "cancel" also applies to a started activity?

**Comment by d-stahl-ericsson** [comment]
In the description in the Eiffel repository I tried to be very explicit on that point.

**Comment by rogpers-ericsson** [comment]
OK. +1 then.

**Pull request merged**
